server:
  port: 31000
spring:
  application:
    name: cms-client
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: xc_cms
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtualHost: /
xuecheng:
  mq:
    #cms客户端监控的队列名称（不同的客户端监控的队列不能重复）
    queue: queue_cms_postpage_03
    # 01 此routingKey为门户站点ID ; 03 是课程详细页面的
    routingKey: 5d8d9d02d7680872649bd695
